services:
  - type: web
    name: college-event-mgmt
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /